"""Public storefront configuration for SPA bootstrapping."""

from fastapi import APIRouter, Depends, Request
from fastapi.responses import JSONResponse, Response

from app.config import settings
from app.db.connection import get_session
from app.services.storefront_resolver import get_public_frontend_config, resolve_frontend_addon
from app.services.push_discovery import build_push_service_worker_js, get_public_push_config
from app.services.site_settings import get_site_settings, site_settings_to_public_dict
from app.services.sso_discovery import get_public_sso_providers
from app.services.tool_discovery import list_storefront_scripts
from schemas.storefront import (
    ActiveFrontendInfo,
    AuthConfigPublic,
    NotificationsConfigPublic,
    PushConfigPublic,
    SiteSettingsPublic,
    SsoProviderPublic,
    StorefrontConfigResponse,
    StorefrontUnavailableResponse,
    ToolsConfigPublic,
)

router = APIRouter(prefix="/storefront", tags=["storefront"])


@router.get(
    "/config",
    response_model=StorefrontConfigResponse,
    responses={
        503: {
            "description": "No frontend addon is enabled",
            "model": StorefrontUnavailableResponse,
        },
    },
    summary="Get storefront bootstrap configuration",
    description="""
Returns merged configuration for the active storefront SPA:

- **`site`**: Site-wide branding from **Admin → Site Settings** (name, colors, fonts, logo).
- **`frontend`**: Active frontend addon id, version, and frontend-specific `config`.

Every storefront must call this on startup. See `app/addons/frontends/README.md`
for integration details and CSS variable names.
    """.strip(),
)
async def get_storefront_config(
    request: Request,
    session=Depends(get_session),
) -> StorefrontConfigResponse:
    frontend = resolve_frontend_addon()
    if frontend is None:
        body = StorefrontUnavailableResponse()
        return JSONResponse(status_code=503, content=body.model_dump())

    site = await get_site_settings(session)
    from app.services.currency import (
        client_country_from_request,
        cookie_currency_preference,
        preferred_currency_hint,
        shop_currency_from_settings,
    )

    site_public = site_settings_to_public_dict(site, request=request)
    shop_currency = shop_currency_from_settings(site)
    site_public["preferred_currency"] = preferred_currency_hint(
        shop_currency=shop_currency,
        ip_country=client_country_from_request(request),
        cookie_preference=cookie_currency_preference(request),
    )
    sso_providers = [
        SsoProviderPublic.model_validate(item) for item in get_public_sso_providers()
    ]
    push_raw = get_public_push_config()
    push_config = PushConfigPublic.model_validate(push_raw) if push_raw else None
    return StorefrontConfigResponse(
        site=SiteSettingsPublic.model_validate(site_public),
        frontend=ActiveFrontendInfo(
            addon_id=frontend.addon_id,
            addon_name=frontend.addon_name,
            version=frontend.version,
            config=get_public_frontend_config(frontend),
        ),
        auth=AuthConfigPublic(
            sso_providers=sso_providers,
            email_verification_enabled=settings.require_email_verification,
        ),
        notifications=NotificationsConfigPublic(push=push_config),
        tools=ToolsConfigPublic(scripts=list_storefront_scripts()),
    )


@router.get(
    "/theme.css",
    response_class=Response,
    summary="Get storefront theme CSS variables",
    description="""
Returns a small CSS file defining `:root` custom properties from site settings.

Link from `index.html` for early paint before JavaScript runs:

```html
<link rel="stylesheet" href="/api/v1/storefront/theme.css" />
```

Variables: `--color-primary`, `--color-secondary`, `--font-sans`.
    """.strip(),
)
async def get_storefront_theme_css(session=Depends(get_session)) -> Response:
    site = await get_site_settings(session)
    css = (
        f":root {{\n"
        f"  --color-primary: {site.primary_color};\n"
        f"  --color-secondary: {site.secondary_color};\n"
        f"  --font-sans: {site.font_family};\n"
        f"}}\n"
    )
    return Response(content=css, media_type="text/css")


@router.get(
    "/push-sw.js",
    response_class=Response,
    summary="Web push service worker",
    description="""
Returns the service worker generated by the enabled push notification addon.
Register from the storefront with scope at site root.
    """.strip(),
)
async def get_push_service_worker() -> Response:
    js = build_push_service_worker_js()
    if js is None:
        return Response(status_code=404, content="Push service worker not available")
    return Response(content=js, media_type="application/javascript")
